inputNPfiles:
    - "dna_r10.4.1_e8.2_400bps_fast@v4.0.0"
    - "dna_r10.4.1_e8.2_400bps_hac@v4.0.0"
    - "dna_r10.4.1_e8.2_400bps_sup@v4.0.0"
    - "dna_r10.4.1_e8.2_400bps_fast@v4.1.0"
    - "dna_r10.4.1_e8.2_400bps_hac@v4.1.0"
    - "dna_r10.4.1_e8.2_400bps_sup@v4.1.0"
npreads:
    - 10000
    - 20000
    - 30000
    - 40000
    - 50000
    - 60000
    - 70000
    - 80000
    - 90000
    - 100000
    - 150000
    - 200000
    - 500000
    - 1000000
reffiles:
    - B.subtilis_hifiasm
    - C.neoformans_hifiasm
    - E.coli_hifiasm
    - E.faecalis_hifiasm
    - L.monocytogenes_hifiasm
    - P.aeruginosa_hifiasm
    - S.aureus_hifiasm
    - S.cerevisiae_hifiasm
    - S.enterica_hifiasm
asmtypes:
    - flye
    - flye.medaka1x
assembly_threads:
     20
polish_threads:
     20
assembly_mb:
     100000
polish_mb:
     100000
medaka_model:
     "r1041_e82_400bps_sup_v4.0.0"
