name: 2023-01-basecalling-benchmarks
channels:
 - conda-forge
 - base
 - R
 - bioconda
dependencies:
 - r-base=4.1.3
 - r-tidyverse=1.3.2
 - r-gridextra=2.3
 - r-rmarkdown=2.14
 - pandoc=2.19.2
 - flye=2.9.1
 - quast=5.2.0
 - fastani=1.33
 - seqtk=1.3
 - bioawk=1.0
 - samtools=1.16.1
 - snakemake=7.18.2
 - nanoplot
 - minimap2=2.24
 - bamtools=2.5.2
 - bcftools=1.19